import {ArticleHead,ArticleBody} from "@/components/Lang";
import VideoEmbed from "@/components/VideoEmbed";
import Link from "next/link";import type {Metadata} from "next";import {ARTICLES,url,fmt,catSlug,abs,slugify} from "@/lib/content";import {Card,Ad,JsonLd,crumbs,ArticleArt} from "@/components/Ui";import {SITE,AUTHORS} from "@/data/site";
export const dynamicParams=false;
export const generateStaticParams=()=>ARTICLES.map(a=>({category:catSlug(a.category),slug:a.slug}));
const get=(s:string)=>ARTICLES.findIndex(a=>a.slug===s);
export function generateMetadata({params}:{params:{slug:string}}):Metadata{const a=ARTICLES[get(params.slug)];const u=url(a);const img=abs(a.image,SITE.url);
return{title:a.title,description:a.excerpt,alternates:{canonical:SITE.url+u},robots:a.demo?{index:false,follow:true}:undefined,openGraph:{type:"article",title:a.title,description:a.excerpt,url:SITE.url+u,images:[img],publishedTime:a.publishedAt,modifiedTime:a.updatedAt,authors:[a.author],section:a.category},twitter:{card:"summary_large_image",title:a.title,description:a.excerpt,images:[img]}}}
export default function Page({params}:{params:{slug:string}}){const i=get(params.slug);const a=ARTICLES[i];const prev=ARTICLES[i+1],next=ARTICLES[i-1];const rel=ARTICLES.filter(x=>x.id!==a.id).slice(0,3);const au=slugify(a.author);const cs=catSlug(a.category);
const share=encodeURIComponent(SITE.url+url(a));
return(<article className={`mx-auto max-w-3xl ${(a.layout==="classic"||a.kind==="explainer")?"nyt":""}`}>
{!a.demo&&<JsonLd d={{"@context":"https://schema.org","@type":"NewsArticle",headline:a.title,description:a.excerpt,image:[abs(a.image,SITE.url)],datePublished:a.publishedAt,dateModified:a.updatedAt,articleSection:a.category,mainEntityOfPage:SITE.url+url(a),author:{"@type":"Person",name:a.author,url:`${SITE.url}/author/${au}`},publisher:{"@type":"Organization",name:SITE.name}}}/>}
<JsonLd d={crumbs([["Home","/"],[a.category,`/category/${cs}`],[a.title,url(a)]])}/>
<nav aria-label="Breadcrumb" className="text-sm text-mute"><Link href="/">Home</Link> / <Link href={`/category/${cs}`}>{a.category}</Link> / <span aria-current="page">{a.title}</span></nav>
{a.demo&&<p role="note" className="mt-3 border border-accent p-2 font-semibold">DEMO ARTICLE — Replace before publication</p>}
<p className="mt-4 font-semibold text-accent">{a.category}</p><ArticleHead title={a.title} excerpt={a.excerpt} i18n={a.i18n}/>
<p className="mt-4 text-sm">By <Link className="underline" href={`/author/${au}`}>{a.author}</Link> · Published <time dateTime={a.publishedAt}>{fmt(a.publishedAt)}</time> · Updated <time dateTime={a.updatedAt}>{fmt(a.updatedAt)}</time></p>
{a.aiAssisted&&<p role="note" className="my-3 rounded border border-line bg-card p-3 text-sm">{a.auto?<>Automatically generated summary, written with AI assistance from reporting by {a.source?.name}. Read the original at the source link in Credits below. </>:<>Transparency: this article was written with AI assistance{a.reviewed?" and reviewed by a BubblesEdiy editor":""} and published by BubblesEdiy. </>}Found an error? See our <Link className="underline" href="/corrections">Corrections Policy</Link>.</p>}<div className="my-5 overflow-hidden rounded"><ArticleArt a={a} priority/></div>{a.imageCredit&&<p className="-mt-3 mb-5 text-xs text-mute">Image: {a.imageCredit}{a.imageSource&&<> (<a className="underline" rel="noopener noreferrer" href={a.imageSource}>source</a>)</>}</p>}
{a.video&&<VideoEmbed v={a.video}/>}{a.video?.poster&&<JsonLd d={{"@context":"https://schema.org","@type":"VideoObject",name:a.video.title||a.title,description:a.excerpt,thumbnailUrl:abs(a.video.poster,SITE.url),uploadDate:a.publishedAt,...(a.video.kind==="file"?{contentUrl:abs(a.video.src||"",SITE.url)}:{embedUrl:a.video.kind==="youtube"?`https://www.youtube.com/embed/${a.video.id}`:`https://player.vimeo.com/video/${a.video.id}`})}}/>}<ArticleBody content={a.content} i18n={a.i18n} reviewed={a.i18nReviewed}/><Ad/>
<div className="flex flex-wrap gap-2" aria-label="Share"><a className="min-h-11 rounded border border-line px-3 py-2" href={`https://twitter.com/intent/tweet?url=${share}`} rel="noopener noreferrer">Share on X</a><a className="min-h-11 rounded border border-line px-3 py-2" href={`https://www.facebook.com/sharer/sharer.php?u=${share}`} rel="noopener noreferrer">Facebook</a><a className="min-h-11 rounded border border-line px-3 py-2" href={`https://wa.me/?text=${share}`} rel="noopener noreferrer">WhatsApp</a></div>
<nav aria-label="Article navigation" className="my-8 grid gap-3 sm:grid-cols-2">{prev&&<Link className="rounded border border-line p-3" href={url(prev)}>Previous: {prev.title}</Link>}{next&&<Link className="rounded border border-line p-3 sm:text-right" href={url(next)}>Next: {next.title}</Link>}</nav>
<section aria-label="Credits" className="mt-6 rounded border border-line p-3 text-sm text-mute"><h2 className="text-base font-bold text-ink">Credits</h2><ul className="mt-1 list-disc pl-5">
{a.imageCredit&&<li>Image: {a.imageCredit}{a.imageSource&&<> · <a className="underline" href={a.imageSource} rel="noopener noreferrer">licence page</a></>}</li>}
{a.video&&<li>Video: {a.video.credit||"BubblesEdiy"}{a.video.kind!=="file"&&` (embedded from ${a.video.kind==="youtube"?"YouTube":"Vimeo"})`}{a.video.ai?" · AI-generated presenter":""}</li>}
{a.source&&<li>Source: <a className="underline" href={a.source.url} rel="noopener noreferrer">{a.source.name}</a></li>}
<li>Written by {a.author}{a.aiAssisted?", with AI assistance":""}</li></ul></section>
<section><h2 className="text-2xl font-bold">About the Author</h2><p className="mt-2 text-mute">{AUTHORS.find(x=>x.slug===au)?.bio} <Link className="underline" href={`/author/${au}`}>Author profile</Link></p></section>
<section className="mt-8"><h2 className="mb-3 text-2xl font-bold">Related News</h2><div className="grid gap-4 sm:grid-cols-3">{rel.map(r=><Card key={r.id} a={r}/>)}</div></section></article>)}
